from pathlib import Path
import yaml
import os

NEGATIVE_INF = -100000.0

PERSPECTIVE_API_KEY = os.environ.get("PERSPECTIVE_API_KEY", None)
PERSPECTIVE_API_KEY = str(PERSPECTIVE_API_KEY)

WANDB_API_KEY = os.environ.get("WANDB_API_KEY", None)
WANDB_API_KEY = str(WANDB_API_KEY)


PERSPECTIVE_API_ATTRIBUTES = {
    'TOXICITY'
}

PERSPECTIVE_API_ATTRIBUTES_LOWER = tuple(a.lower() for a in PERSPECTIVE_API_ATTRIBUTES)
